### ISSUE TITLE
Impossible to start on Windows environment

### ISSUE THREAD

**Issue by sgalopin** [geoext/geoext3-ws#2]
0 info it worked if it ends with ok
1 verbose cli [ 'c:\Program Files\nodejs\node.exe',
1 verbose cli   'c:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@1.4.9
3 info using node@v0.10.28
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart geoext3-ws@0.0.1
6 info start geoext3-ws@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info geoext3-ws@0.0.1 Failed to exec start script
9 error geoext3-ws@0.0.1 start: `mkdir -p src/_book && npm run doc:serve`
9 error Exit status 1
10 error Failed at the geoext3-ws@0.0.1 start script.
10 error This is most likely a problem with the geoext3-ws package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     mkdir -p src/_book && npm run doc:serve
10 error You can get their info via:
10 error     npm owner ls geoext3-ws
10 error There is likely additional logging output above.
11 error System Windows_NT 6.1.7601
12 error command "c:\Program Files\nodejs\node.exe" "c:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
13 error cwd c:\Users\sgalopin\Desktop\geoext3-ws-master
14 error node -v v0.10.28
15 error npm -v 1.4.9
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

**Comment by marcjansen** [comment]
Huh... cool someone actually tests this!

Can you give me the versions of npm and node?

I assume you did `npm install`, right?

**Comment by marcjansen** [comment]
Aaaah... I see the versioms in your log output. Could you try to upgrade to nodejs 4?

I have never tried on windows.

**Comment by marcjansen** [comment]
The `mkdir` command is likely to fail for you, regardless of the node version. Pull requests for more OS indewndency very welcome!

**Comment by chrismayer** [comment]
Setting up the HTML with `npm i && npm start` works fine for me with `node.js v5.0.0` and `npm v3.5.0` on a Linux machine.

**Comment by marcjansen** [comment]
Extra cool, @chrismayer! Glad to hear that! Are you runnig the npm commands from the standard commandline n windows or the gitshell (however that is actually called)

I am a bit surprised that `mkdir` works... or is the command the same on windows and linux. It's been a while for me :wink:

**Comment by chrismayer** [comment]
I just tested on a Windows 8 machine and I got the following error (as expected):

```
> mkdir -p src/_book && npm run doc:ser

The syntax of the command is incorrect.
```

This happens on the default cmd interface as well as on the git shell cmd line interface.

**Comment by chrismayer** [comment]
Ooops, :open_mouth: I guess we have a duplicate here.
Seems we did the same fix parallely @marcjansen. Which do we take? Yours seems to be a bit less code, so maybe this?

**Comment by sgalopin** [comment]
@chrismayer Thank i think it's the best to do (node script).
In the interval, i use that quick solution:
    "clean": "(if exist src\_book rmdir /S /Q src\_book) && (if exist build rmdir /S /Q build)",
    "start": "(if not exist src\_book mkdir src\_book) && npm run doc:serve",

**Comment by marcjansen** [comment]
@chrismayer Both proposed solutions are OK from me, I'd favor mine of course :octopus: :octopus: .

Are we sure they both fix the issue on ewondows?

**Comment by marcjansen** [comment]
@sullianmccornic are you saying that the `clean target` also errors out?

**Comment by sgalopin** [comment]
It's fix the issue on my Windows_NT 6.1.7601 for the commands:
npm start
npm run clean
But I've not rectify the target check:calibre and check:zip on windows and I've not tryed all the targets...

**Comment by marcjansen** [comment]
I think #5  should give us a lot of scripts on all OSes

**Comment by sgalopin** [comment]
@afi : I think too! Thank for your work!

**Comment by chrismayer** [comment]
With the merge of #5 this should be fine. Thanks to all!
