### ISSUE TITLE
Adapt SymbolizerColumn section in "Create a feature grid" exercise

### ISSUE THREAD

**Issue by chrismayer** [geoext/geoext3-ws#24]
Due to the removal of the `GeoExt.grid.column.Symbolizer` in https://github.com/geoext/geoext3/pull/168 the workshop exercise "Create a feature grid" ( defined [here](https://github.com/geoext/geoext3-ws/blob/master/src/feature-grid/create.md) ) has to be adapted.

**Comment by marcjansen** [comment]
Working on this tomorrow.
